name: Release

on:
  push:
    branches:
      - master
      - next

jobs:
  Release:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [12.x] # 10.x, 12.x, 14.x
    steps:
      - name: Checkout branch.
        uses: actions/checkout@master
      - name: Setup git.
        run: |
          git config user.name "Action"
          git config user.email "rafegoldberg@gmail.com"
      - name: Setup node. (v${{ matrix.node-version }})
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install package dependencies.
        run: |
          npm ci
          npm run build --if-present
        env:
          CI: true
      - name: Build and publish a new release.
        run: |
          npx semantic-release --debug --dryRun
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # publish to GitHub remote
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}   # release to NPM registry
      - name: Sync release changes to remote.
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}
        continue-on-error: true
      - name: Archive the bundle.
        uses: actions/upload-artifact@v1
        with:
          name: Bundle
          path: dist
        continue-on-error: true
