name: Release

on:
  push:
    branches:
      - master
      - next

jobs:
  semantic-release:
    name: Release
    if: "!contains(github.event.head_commit.message, 'SKIP CI')"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [12.x] # 10.x, 12.x, 14.x
    steps:
      - name: Checkout branch (${{ github.ref }})
        uses: actions/checkout@master
      - name: Configure git
        run: |
          git config user.name "Action"
          git config user.email "rafegoldberg@gmail.com"
      - name: Setup node (v${{ matrix.node-version }})
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install packages
        run: |
          npm ci
          npm run build --if-present
        env:
          CI: true
      - name: Build release
        run: npx semantic-release # --debug # --dryRun
        env:
          GH_TOKEN: ${{ secrets.GITHUB_ADMIN || secrets.GITHUB_TOKEN }} # publish to GitHub
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }} # release to NPM (if configured in .releaserc)
      - name: Sync to remote
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
        continue-on-error: true
      - name: Sync to next
        if: "github.ref == 'refs/heads/master'"
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: next
        continue-on-error: true
      - name: Save bundle
        uses: actions/upload-artifact@v1
        with:
          name: Bundle
          path: dist
        continue-on-error: true
